name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- uses: actions/setup-python@v3
      - name: Make conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: sphinx_documentation
          python-version: 3.11
          environment-file: environment.yml    # Path to the documentation conda environment
          channels: conda-forge,defaults
          channel-priority: strict
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true #- name: Install dependencies
      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list
      - name: Sphinx build
        run: |
          sphinx-build source _build/html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build
          force_orphan: true